language: python
python:
  - "2.6"

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y python-lxml

# install: DEPENDENCIES

# command to run tests
script: make && make validate
