# platform = multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
- (xccdf-var var_selinux_state)

- name: "@RULE_TITLE@"
  selinux:
    state: "{{ var_selinux_state }}"
  tags:
    @ANSIBLE_TAGS@
